# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\Education\C++\cmake-3.12.3-win64-x64\bin\cmake.exe

# The command to remove a file.
RM = D:\Education\C++\cmake-3.12.3-win64-x64\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Education\C++\projects\Sieve_of_Eratosthenes\v3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Education\C++\projects\Sieve_of_Eratosthenes\v3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	D:\Education\C++\cmake-3.12.3-win64-x64\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	D:\Education\C++\cmake-3.12.3-win64-x64\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Education\C++\projects\Sieve_of_Eratosthenes\v3\CMakeFiles D:\Education\C++\projects\Sieve_of_Eratosthenes\v3\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Education\C++\projects\Sieve_of_Eratosthenes\v3\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named prime_integer

# Build rule for target.
prime_integer: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 prime_integer
.PHONY : prime_integer

# fast build rule for target.
prime_integer/fast:
	$(MAKE) -f CMakeFiles\prime_integer.dir\build.make CMakeFiles/prime_integer.dir/build
.PHONY : prime_integer/fast

Sieve_Eratosthen.obj: Sieve_Eratosthen.cpp.obj

.PHONY : Sieve_Eratosthen.obj

# target to build an object file
Sieve_Eratosthen.cpp.obj:
	$(MAKE) -f CMakeFiles\prime_integer.dir\build.make CMakeFiles/prime_integer.dir/Sieve_Eratosthen.cpp.obj
.PHONY : Sieve_Eratosthen.cpp.obj

Sieve_Eratosthen.i: Sieve_Eratosthen.cpp.i

.PHONY : Sieve_Eratosthen.i

# target to preprocess a source file
Sieve_Eratosthen.cpp.i:
	$(MAKE) -f CMakeFiles\prime_integer.dir\build.make CMakeFiles/prime_integer.dir/Sieve_Eratosthen.cpp.i
.PHONY : Sieve_Eratosthen.cpp.i

Sieve_Eratosthen.s: Sieve_Eratosthen.cpp.s

.PHONY : Sieve_Eratosthen.s

# target to generate assembly for a file
Sieve_Eratosthen.cpp.s:
	$(MAKE) -f CMakeFiles\prime_integer.dir\build.make CMakeFiles/prime_integer.dir/Sieve_Eratosthen.cpp.s
.PHONY : Sieve_Eratosthen.cpp.s

prime_integer.obj: prime_integer.cpp.obj

.PHONY : prime_integer.obj

# target to build an object file
prime_integer.cpp.obj:
	$(MAKE) -f CMakeFiles\prime_integer.dir\build.make CMakeFiles/prime_integer.dir/prime_integer.cpp.obj
.PHONY : prime_integer.cpp.obj

prime_integer.i: prime_integer.cpp.i

.PHONY : prime_integer.i

# target to preprocess a source file
prime_integer.cpp.i:
	$(MAKE) -f CMakeFiles\prime_integer.dir\build.make CMakeFiles/prime_integer.dir/prime_integer.cpp.i
.PHONY : prime_integer.cpp.i

prime_integer.s: prime_integer.cpp.s

.PHONY : prime_integer.s

# target to generate assembly for a file
prime_integer.cpp.s:
	$(MAKE) -f CMakeFiles\prime_integer.dir\build.make CMakeFiles/prime_integer.dir/prime_integer.cpp.s
.PHONY : prime_integer.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... rebuild_cache
	@echo ... prime_integer
	@echo ... edit_cache
	@echo ... Sieve_Eratosthen.obj
	@echo ... Sieve_Eratosthen.i
	@echo ... Sieve_Eratosthen.s
	@echo ... prime_integer.obj
	@echo ... prime_integer.i
	@echo ... prime_integer.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

